apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simplewebservice-argo-application
  namespace: whaka
spec:
  project: default
  source:
    repoURL: https://github.com/RobinMilissenPXL/Argocd-testapp.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: whaka

  syncPolicy:
    syncOptions:
      - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true
