apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwebservice
spec:
  selector:
    matchLabels:
      app: testwebservice
  replicas: 3
  template:
    metadata:
      labels:
        app: testwebservice
    spec:
      containers:
        - name: testwebservice
          image: milissenrobin/milissenrobinpxl:calculator-app
          ports:
            - containerPort: 8080
